import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faBlogger,
  faGithub,
  faInstagram,
} from "@fortawesome/free-brands-svg-icons";
import type { Metadata } from "next";
import style from "./layout.module.css";
import "./globals.css";
import "./reset.css";
import Link from "next/link";
import { faArrowRight, faBlog } from "@fortawesome/free-solid-svg-icons";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function Header() {
  return (
    <header>
      <div className={style.headerBody}>
        <h1>
          <Link href={"/"}>2025 portfolio</Link>
        </h1>
        <div className={style.headerIcon}>
          <div>
            <Link href={"/"}>
              <FontAwesomeIcon icon={faBlogger} />
              <span className={style.hide}>블로그</span>
            </Link>
          </div>
          <div>
            <Link href={"/"}>
              <FontAwesomeIcon icon={faGithub} />
              <span className={style.hide}>깃허브</span>
            </Link>
          </div>
          <div>
            <Link href={"/"}>
              <FontAwesomeIcon icon={faInstagram} />
              <span className={style.hide}>인스타</span>
            </Link>
          </div>
        </div>
      </div>
    </header>
  );
}

async function Footer() {
  return <footer>제작 ©HongSinWon_Portfolio@2025</footer>;
}

async function ScrollButton() {
  return (
    <div>
      <button>
        <FontAwesomeIcon icon={faArrowRight} />
      </button>
      <button>
        <FontAwesomeIcon icon={faArrowRight} />
      </button>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className={style.container}>
          <Header />
          <main>{children}</main>
          <Footer />
          <ScrollButton />
        </div>
      </body>
    </html>
  );
}
